### ISSUE TITLE
v4 api does not always return things correctly if &pretty attribute is used or vice versa

### ISSUE THREAD

**Issue by olli-suutari-jkl** [libraries-fi/kirkanta-api#3]
https://api.kirjastot.fi/v4/schedules?library=85306&lang=fi&period.start=1w&period.end=1w&refs=period&pretty 

returns: 
"date": "2019-02-18",
"info": "Aukioloajat",

But:

https://api.kirjastot.fi/v4/schedules?library=85306&lang=fi&period.start=1w&period.end=1w&refs=period

returns:
date":"2019-02-18",
"info":null,

Note: I will remove the day info later today since the library is Live.
The results via Gist: https://gist.github.com/olli-suutari-jkl/d87c9a540b6c2b54e4a6ad26e348ea6b

**Comment by olli-suutari-jkl** [comment]
The same thing was happening with &refs=period , but for now both queries appear to be working?

This returns the special schedule correctly: 
https://api.kirjastot.fi/v4/schedules?library=85306&lang=fi&period.start=1w&period.end=1w&refs=period&pretty
    
"refs": {
        "period": {
            "330731": {
                "id": 330731,
                "library": 85306,
                "validFrom": "2019-02-18",
                "validUntil": "2019-02-24",
                "isException": true,
                "name": "testi",
                "description": "Testi"
            }
        }
    }

The same without &pretty returns the normal schedule, but the description is null instead
https://api.kirjastot.fi/v4/schedules?library=85306&lang=fi&period.start=1w&period.end=1w&refs=period

**Comment by olli-suutari-jkl** [comment]
Today I created a special schedule for next weeks thursday.
Now &pretty attribute causes the current weeks schedule info to return as null, where ass without &pretty it is returned correctly.

https://api.kirjastot.fi/v4/schedules?library=85306&lang=fi&period.start=0w&period.end=0w&refs=period

https://api.kirjastot.fi/v4/schedules?library=85306&lang=fi&period.start=0w&period.end=0w&refs=period&pretty

See: https://gist.github.com/olli-suutari-jkl/4df5cbd60140b511ca75c4feb0616f66

Gif demonstration:
![pretty attribute messing](https://user-images.githubusercontent.com/42733913/52696898-dfde9c80-2f78-11e9-86a0-b2435c8ec6f1.gif)

**Comment by sjuvonen** [comment]
The flag 'pretty' does not do anything else except pass indentation level to the native JSON formatter so it is very unlikely that it has got anything to do with the issues. The API does employ caching headers so my guess is that you're just seeing cached values. Caching is purely a client-side thing so you can disable it from Firefox or Chrome etc.

**Comment by olli-suutari-jkl** [comment]
That makes sense, for how long are the values cached? 

The maintainers of kirkanta lib details are frequently confused, because  they cannot see the changes in the public interface within an hour or so, because they test it within the same browser. @sjuvonen.

**Comment by sjuvonen** [comment]
Right now the default value for caching is about 24 hours. I think it's the responsibility of the "client application" to circumvent caching if need be. We don't strictly force caching (i.e. no transparent server-side caching), the response only contains caching instructions in headers.

**Comment by sjuvonen** [comment]
As a side note, caching instructions obviously have to be a little bit shorter when used in conjunction with relative period intervals, so that tweak might solve your issues anyway. I am gonna work on it later today. Maybe we set the caching down to one hour with those parameters.

**Comment by olli-suutari-jkl** [comment]
I have now fully disabled caching of the data.
This will presumably increase the requests made from:
https://www.keskikirjastot.fi and https://www.jyvaskyla.fi/kirjasto/kirjastot .

**Comment by sjuvonen** [comment]
It's just very frustrating for users to suffer of slow widgets, that is why caching is there in the first place...

**Comment by olli-suutari-jkl** [comment]
Yeah... I've modified it so that only $.getJSON requests are no longer cached, should not add too much of a delay unless the whole db starts lagging.

https://github.com/olli-suutari-jkl/jyvaskyla.fi.kirjasto/commit/ef9211c67770fb15c25656488a247dab303a4a4a

**Comment by sjuvonen** [comment]
Network lag on a slow and unstable (mobile) connection is the main issue and it is really unpredictable. Usually it is also not accounted for in the widget design which causes confusion when nothing seems to happen or things appear broken.
