### ISSUE TITLE
Building details (founded, building, year built, aritecht & decoration) are not available via v4 api

### ISSUE THREAD

**Issue by olli-suutari-jkl** [libraries-fi/kirkanta-api#5]
In v3 the trivia details mentioned in the title were available with=extra.
https://api.kirjastot.fi/v3/library/85159?lang=fi&with=extra

However, in v4 there appears to be no equivalent of it, or at least I can't find documentation for it here:
https://api.kirjastot.fi/

https://api.kirjastot.fi/v4/library/85159?lang=fi&with=extra&pretty&limit=500

**Comment by sjuvonen** [comment]
I will fix this later today.

**Comment by sjuvonen** [comment]
Foundation year is now restored to **library.founded**. Rest of the data is in a new optional block **library.buildingInfo** (with=buildingInfo).

Documentation is also updated but browser cache should be refreshed.
