### ISSUE TITLE
v4 Api includes "hidden" persons in &with=persons

### ISSUE THREAD

**Issue by olli-suutari-jkl** [libraries-fi/kirkanta-api#6]
v4 api returns all of the staff listed to a library, instead of fetching only those that are visible.

See:
https://api.kirjastot.fi/v4/library/85159?lang=fi&with=persons&pretty
https://api.kirjastot.fi/v3/library/85159?lang=fi&with=persons

**Comment by sjuvonen** [comment]
This has been fixed on March 16.
https://github.com/libraries-fi/kirkanta/commit/64b714a664c782e05b1fe1fef6cb6f5837c3b0a7
