### ISSUE TITLE
V4 Api sometimes returns closed in between time even though it should not (status 0)

### ISSUE THREAD

**Issue by olli-suutari-jkl** [libraries-fi/kirkanta-api#8]
https://api.kirjastot.fi/v4/schedules?library=85713&lang=en&period.start=0w&period.end=0w&refs=period&limit=5000&pretty

**Here we have a schedule row for today, which returns 4 items:**
Self-service: 7-11
**Closed: 11-16**
Staff: 11-16
Self-service: 16-21

        {
            "library": 85713,
            "period": 333449,
            "date": "2019-04-30",
            "info": null,
            "closed": false,
            "times": [
                {
                    "to": "11:00",
                    "from": "07:00",
                    "status": 2
                },
                {
                    "to": "16:00",
                    "from": "11:00",
                    "status": 0
                },
                {
                    "to": "16:00",
                    "from": "11:00",
                    "status": 1
                },
                {
                    "to": "21:00",
                    "from": "16:00",
                    "status": 2
                }
            ]
        },

Full result: https://gist.github.com/olli-suutari-jkl/fde7c7a51a5b32df41e45b04d3883a39

https://kirkanta.kirjastot.fi/library/85713/periods

![image](https://user-images.githubusercontent.com/42733913/56947923-3d759480-6b37-11e9-851e-26d1dd1f74be.png)

![image](https://user-images.githubusercontent.com/42733913/56947948-48302980-6b37-11e9-9195-b93ca205528a.png)

![image](https://user-images.githubusercontent.com/42733913/56947983-5b42f980-6b37-11e9-9988-bdeccb6ac2dc.png)

**Comment by sjuvonen** [comment]
I'll look into it.

**Comment by olli-suutari-jkl** [comment]
Thanks, it may or may not have something to do with the fact that the schedule for 30.4. is entered to kirkanta in a "wrong order" (11-16 > 7-11 >16-21). Which I suppose is a bug in https://kirkanta.kirjastot.fi/ -interface.

**Comment by sjuvonen** [comment]
Well it is just assumed that users would know to fill in schedules in chronological order but I guess not then. It should be possible to sort the entries before saving so it should be an easy fix.

**Comment by sjuvonen** [comment]
Fixed with https://github.com/libraries-fi/kirkanta/commit/05bae27dd54a391cf43d2fdd9db2c1aaaab9162c.
